[workspace]
members = [
    "chapter01-helloworld",
    "chapter02-guessing-game", "chapter03-common-concepts", "chapter04-ownership"]
resolver = "3"

[workspace.package]
publish = false

[workspace.dependencies]
